export interface StoredObject {
  body: Buffer;
  contentType: string | null;
}

/**
 * Minimal object store used for guest ID images. Selected by STORAGE_DRIVER:
 * `local` (a directory on disk, for development and single-node installs) or
 * `s3` (any S3-compatible service: AWS S3, Cloudflare R2, MinIO, DO Spaces).
 */
export interface ObjectStorage {
  readonly driver: 'local' | 's3';
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
  /** M6: removes every object under a prefix ("tenants/<id>/"); returns how many. */
  deletePrefix(prefix: string): Promise<number>;
}

export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

/** Keys are generated by the API; this guards against path tricks anyway. */
export function assertSafeKey(key: string): void {
  if (!/^[a-zA-Z0-9/_.-]+$/.test(key) || key.includes('..') || key.startsWith('/')) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}
