-- M5, part 1: enum values (own migration: a value added with ALTER TYPE ...
-- ADD VALUE cannot be used in the same transaction).
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'WAITER';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'KITCHEN';

ALTER TYPE "GuardRule" ADD VALUE IF NOT EXISTS 'POS_VOID_AFTER_SEND';
ALTER TYPE "GuardRule" ADD VALUE IF NOT EXISTS 'ROOM_CHARGE_NO_GUEST';
ALTER TYPE "GuardRule" ADD VALUE IF NOT EXISTS 'STOCK_VARIANCE';
ALTER TYPE "GuardRule" ADD VALUE IF NOT EXISTS 'POS_OPEN_TABS_AT_SHIFT_CLOSE';
ALTER TYPE "GuardRule" ADD VALUE IF NOT EXISTS 'OVERBOOKED';
ALTER TYPE "GuardRule" ADD VALUE IF NOT EXISTS 'LOYALTY_ADJUSTMENT';

ALTER TYPE "FolioKind" ADD VALUE IF NOT EXISTS 'POS';

ALTER TYPE "DocumentCounterKind" ADD VALUE IF NOT EXISTS 'POS_ORDER';
ALTER TYPE "DocumentCounterKind" ADD VALUE IF NOT EXISTS 'KDS_TICKET';
ALTER TYPE "DocumentCounterKind" ADD VALUE IF NOT EXISTS 'LOYALTY_MEMBER';
