-- M6: Enterprise tier and the hardened platform console (tables generated by Prisma,
-- RLS, grants, append-only rules and the purge authorisation written by hand below).

-- AlterTable
ALTER TABLE "invoices" ADD COLUMN     "coupon_code" TEXT,
ADD COLUMN     "discount_kobo" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "platform_users" ADD COLUMN     "failed_attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "invite_expires_at" TIMESTAMPTZ(3),
ADD COLUMN     "invite_token_hash" TEXT,
ADD COLUMN     "invited_by_id" UUID,
ADD COLUMN     "ip_allowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "locked_until" TIMESTAMPTZ(3),
ADD COLUMN     "mfa_enabled_at" TIMESTAMPTZ(3),
ADD COLUMN     "password_changed_at" TIMESTAMPTZ(3),
ADD COLUMN     "totp_pending_secret_enc" TEXT,
ADD COLUMN     "totp_secret_enc" TEXT;

-- AlterTable
ALTER TABLE "subscriptions" ADD COLUMN     "contract_end_at" TIMESTAMPTZ(3),
ADD COLUMN     "contract_notes" TEXT,
ADD COLUMN     "contract_start_at" TIMESTAMPTZ(3),
ADD COLUMN     "custom_price_kobo" INTEGER;

-- AlterTable
ALTER TABLE "tenants" ADD COLUMN     "deleted_at" TIMESTAMPTZ(3),
ADD COLUMN     "lifecycle" TEXT NOT NULL DEFAULT 'ACTIVE';

-- CreateTable
CREATE TABLE "platform_recovery_codes" (
    "id" UUID NOT NULL,
    "platform_user_id" UUID NOT NULL,
    "code_hash" TEXT NOT NULL,
    "used_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_recovery_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_sessions" (
    "id" UUID NOT NULL,
    "platform_user_id" UUID NOT NULL,
    "ip" TEXT,
    "user_agent" TEXT,
    "mfa_method" TEXT NOT NULL DEFAULT 'totp',
    "step_up_at" TIMESTAMPTZ(3),
    "last_seen_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "revoked_at" TIMESTAMPTZ(3),
    "revoke_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_refresh_tokens" (
    "id" UUID NOT NULL,
    "session_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "rotated_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_audit_logs" (
    "id" UUID NOT NULL,
    "actor_platform_user_id" UUID,
    "actor_name" TEXT,
    "actor_role" TEXT,
    "action" TEXT NOT NULL,
    "target_type" TEXT,
    "target_id" TEXT,
    "tenant_id" UUID,
    "method" TEXT,
    "path" TEXT,
    "status_code" INTEGER,
    "ip" TEXT,
    "user_agent" TEXT,
    "session_id" UUID,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "coupons" (
    "id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "percent_off" INTEGER,
    "amount_off_kobo" INTEGER,
    "duration_months" INTEGER,
    "plan_codes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "intervals" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "max_redemptions" INTEGER,
    "redemptions" INTEGER NOT NULL DEFAULT 0,
    "valid_from" TIMESTAMPTZ(3),
    "valid_until" TIMESTAMPTZ(3),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID,
    "created_by_name" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "coupons_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "coupon_redemptions" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "coupon_id" UUID NOT NULL,
    "months_remaining" INTEGER,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "applied_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMPTZ(3),

    CONSTRAINT "coupon_redemptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "announcements" (
    "id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "severity" TEXT NOT NULL DEFAULT 'INFO',
    "audience" JSONB NOT NULL DEFAULT '{"kind":"ALL"}',
    "in_app" BOOLEAN NOT NULL DEFAULT true,
    "email" BOOLEAN NOT NULL DEFAULT false,
    "starts_at" TIMESTAMPTZ(3) NOT NULL,
    "ends_at" TIMESTAMPTZ(3),
    "dismissible" BOOLEAN NOT NULL DEFAULT true,
    "link_label" TEXT,
    "link_url" TEXT,
    "published_at" TIMESTAMPTZ(3),
    "ended_at" TIMESTAMPTZ(3),
    "archived_at" TIMESTAMPTZ(3),
    "emailed_at" TIMESTAMPTZ(3),
    "targeted_tenants" INTEGER NOT NULL DEFAULT 0,
    "emails_sent" INTEGER NOT NULL DEFAULT 0,
    "created_by_id" UUID,
    "created_by_name" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "announcements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "announcement_receipts" (
    "id" UUID NOT NULL,
    "announcement_id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "seen_at" TIMESTAMPTZ(3),
    "dismissed_at" TIMESTAMPTZ(3),

    CONSTRAINT "announcement_receipts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "support_requests" (
    "id" UUID NOT NULL,
    "seq" SERIAL NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID,
    "property_name" TEXT,
    "opened_by_id" UUID NOT NULL,
    "opened_by_name" TEXT NOT NULL,
    "opened_by_email" TEXT NOT NULL,
    "opened_by_role" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'NORMAL',
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "plan_code" TEXT NOT NULL,
    "sla_hours" INTEGER NOT NULL,
    "first_response_due" TIMESTAMPTZ(3) NOT NULL,
    "first_responded_at" TIMESTAMPTZ(3),
    "assignee_id" UUID,
    "assignee_name" TEXT,
    "context" JSONB NOT NULL DEFAULT '{}',
    "last_message_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "hotel_read_at" TIMESTAMPTZ(3),
    "platform_read_at" TIMESTAMPTZ(3),
    "last_hotel_msg_at" TIMESTAMPTZ(3),
    "last_platform_msg_at" TIMESTAMPTZ(3),
    "resolved_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "support_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "support_messages" (
    "id" UUID NOT NULL,
    "request_id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "author_kind" TEXT NOT NULL,
    "author_id" UUID NOT NULL,
    "author_name" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "internal" BOOLEAN NOT NULL DEFAULT false,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "support_messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "support_attachments" (
    "key" TEXT NOT NULL,
    "tenant_id" UUID,
    "uploaded_by_kind" TEXT NOT NULL,
    "uploaded_by_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "size" INTEGER NOT NULL,
    "content_type" TEXT NOT NULL,
    "message_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "support_attachments_pkey" PRIMARY KEY ("key")
);

-- CreateTable
CREATE TABLE "impersonation_sessions" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "user_name" TEXT NOT NULL,
    "user_email" TEXT NOT NULL,
    "user_role" TEXT NOT NULL,
    "platform_user_id" UUID NOT NULL,
    "platform_user_name" TEXT NOT NULL,
    "platform_user_email" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "write_reason" TEXT,
    "mode" TEXT NOT NULL DEFAULT 'READ_ONLY',
    "started_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "ended_at" TIMESTAMPTZ(3),
    "ended_by" TEXT,
    "support_request_id" UUID,
    "handoff_code_hash" TEXT,
    "handoff_expires_at" TIMESTAMPTZ(3),
    "handoff_used_at" TIMESTAMPTZ(3),
    "requests" INTEGER NOT NULL DEFAULT 0,
    "writes" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "impersonation_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenant_offboardings" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "tenant_name" TEXT NOT NULL,
    "tenant_slug" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'EXPORTING',
    "reason" TEXT NOT NULL,
    "previous_status" TEXT,
    "requested_by_id" UUID,
    "requested_by_name" TEXT NOT NULL,
    "requested_by_email" TEXT,
    "requested_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "export_id" UUID,
    "delete_after" TIMESTAMPTZ(3),
    "deleted_at" TIMESTAMPTZ(3),
    "cancelled_at" TIMESTAMPTZ(3),
    "cancelled_by_id" UUID,
    "cancelled_by_name" TEXT,
    "summary" JSONB,
    "error" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "tenant_offboardings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "data_exports" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'QUEUED',
    "reason" TEXT NOT NULL DEFAULT 'REQUEST',
    "requested_by_kind" TEXT NOT NULL,
    "requested_by_id" UUID NOT NULL,
    "requested_by_name" TEXT NOT NULL,
    "formats" TEXT[] DEFAULT ARRAY['json', 'csv']::TEXT[],
    "progress_pct" INTEGER NOT NULL DEFAULT 0,
    "entities" JSONB NOT NULL DEFAULT '[]',
    "size_bytes" INTEGER,
    "file_key" TEXT,
    "file_name" TEXT,
    "link_expires_at" TIMESTAMPTZ(3),
    "delete_file_after" TIMESTAMPTZ(3),
    "finished_at" TIMESTAMPTZ(3),
    "error" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "data_exports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenant_databases" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "mode" TEXT NOT NULL DEFAULT 'SHARED',
    "status" TEXT,
    "url_enc" TEXT,
    "app_url_enc" TEXT,
    "platform_url_enc" TEXT,
    "db_name" TEXT,
    "host" TEXT,
    "created_by_us" BOOLEAN NOT NULL DEFAULT false,
    "version" TEXT,
    "last_migrated_at" TIMESTAMPTZ(3),
    "activated_at" TIMESTAMPTZ(3),
    "read_only_until" TIMESTAMPTZ(3),
    "shared_purge_after" TIMESTAMPTZ(3),
    "shared_purged_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "tenant_databases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "db_provisionings" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'PROVISION',
    "status" TEXT NOT NULL DEFAULT 'PROVISIONING',
    "step" TEXT NOT NULL DEFAULT 'CREATE_DATABASE',
    "progress_pct" INTEGER NOT NULL DEFAULT 0,
    "source" TEXT NOT NULL DEFAULT 'AUTO',
    "requested_by_id" UUID,
    "requested_by_name" TEXT,
    "read_only_started_at" TIMESTAMPTZ(3),
    "read_only_ended_at" TIMESTAMPTZ(3),
    "tables" JSONB NOT NULL DEFAULT '[]',
    "logs" JSONB NOT NULL DEFAULT '[]',
    "error" TEXT,
    "started_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finished_at" TIMESTAMPTZ(3),

    CONSTRAINT "db_provisionings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public_listings" (
    "property_id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "tenant_slug" TEXT NOT NULL,
    "tenant_name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "area" TEXT NOT NULL DEFAULT '',
    "tagline" TEXT NOT NULL DEFAULT '',
    "cover_image_url" TEXT,
    "listed" BOOLEAN NOT NULL DEFAULT true,
    "suspended" BOOLEAN NOT NULL DEFAULT false,
    "dedicated" BOOLEAN NOT NULL DEFAULT false,
    "custom_domain" TEXT,
    "custom_domain_verified" BOOLEAN NOT NULL DEFAULT false,
    "starting_rate_kobo" INTEGER,
    "rating" DOUBLE PRECISION,
    "review_count" INTEGER NOT NULL DEFAULT 0,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "property_created_at" TIMESTAMPTZ(3) NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "public_listings_pkey" PRIMARY KEY ("property_id")
);

-- CreateTable
CREATE TABLE "job_runs" (
    "job" TEXT NOT NULL,
    "queue" TEXT NOT NULL,
    "last_run_at" TIMESTAMPTZ(3),
    "last_finished_at" TIMESTAMPTZ(3),
    "last_status" TEXT,
    "last_duration_ms" INTEGER,
    "last_error" TEXT,
    "runs" INTEGER NOT NULL DEFAULT 0,
    "failures" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "job_runs_pkey" PRIMARY KEY ("job")
);

-- CreateTable
CREATE TABLE "owner_setup_tokens" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "used_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "owner_setup_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "api_keys" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "environment" TEXT NOT NULL DEFAULT 'LIVE',
    "prefix" TEXT NOT NULL,
    "secret_hash" TEXT NOT NULL,
    "last4" TEXT NOT NULL,
    "previous_secret_hash" TEXT,
    "previous_last4" TEXT,
    "previous_expires_at" TIMESTAMPTZ(3),
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "property_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "ip_allowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "expires_at" TIMESTAMPTZ(3),
    "revoked_at" TIMESTAMPTZ(3),
    "created_by_id" UUID,
    "created_by_name" TEXT,
    "last_used_at" TIMESTAMPTZ(3),
    "last_used_ip" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "api_usage_daily" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "api_key_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "requests" INTEGER NOT NULL DEFAULT 0,
    "errors" INTEGER NOT NULL DEFAULT 0,
    "writes" INTEGER NOT NULL DEFAULT 0,
    "rate_limited" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "api_usage_daily_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "white_label_settings" (
    "tenant_id" UUID NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "brand_name" TEXT,
    "logo_url" TEXT,
    "favicon_url" TEXT,
    "primary_color" TEXT,
    "accent_color" TEXT,
    "heading_font" TEXT,
    "body_font" TEXT,
    "footer_links" JSONB NOT NULL DEFAULT '[]',
    "hide_powered_by" BOOLEAN NOT NULL DEFAULT true,
    "email_from_name" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "white_label_settings_pkey" PRIMARY KEY ("tenant_id")
);

-- CreateTable
CREATE TABLE "email_domains" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "domain" TEXT NOT NULL,
    "from_local_part" TEXT NOT NULL DEFAULT 'reservations',
    "provider" TEXT NOT NULL DEFAULT 'mock',
    "provider_domain_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NOT_STARTED',
    "records" JSONB NOT NULL DEFAULT '[]',
    "last_checked_at" TIMESTAMPTZ(3),
    "verified_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "email_domains_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sms_sender_requests" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "sender_id" TEXT NOT NULL,
    "use_case" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "note" TEXT,
    "provider" TEXT NOT NULL DEFAULT 'mock',
    "provider_ref" TEXT,
    "current" BOOLEAN NOT NULL DEFAULT true,
    "requested_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "decided_at" TIMESTAMPTZ(3),
    "decided_by_name" TEXT,

    CONSTRAINT "sms_sender_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "staff_portal_domains" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "domain" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "token" TEXT NOT NULL,
    "failures" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "txt_ok" BOOLEAN,
    "cname_ok" BOOLEAN,
    "check_count" INTEGER NOT NULL DEFAULT 0,
    "last_checked_at" TIMESTAMPTZ(3),
    "verified_at" TIMESTAMPTZ(3),
    "failing_since" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "staff_portal_domains_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sso_configs" (
    "tenant_id" UUID NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "provider" TEXT NOT NULL DEFAULT 'OIDC',
    "issuer" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "client_secret_enc" TEXT,
    "client_secret_last4" TEXT,
    "allowed_domains" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "provisioning" TEXT NOT NULL DEFAULT 'EXISTING_ONLY',
    "default_role" TEXT NOT NULL DEFAULT 'FRONT_DESK',
    "enforced" BOOLEAN NOT NULL DEFAULT false,
    "break_glass_user_id" UUID,
    "last_test_at" TIMESTAMPTZ(3),
    "last_test_ok" BOOLEAN,
    "last_test_message" TEXT,
    "last_test_email" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "sso_configs_pkey" PRIMARY KEY ("tenant_id")
);

-- CreateTable
CREATE TABLE "webhook_endpoints" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "url" TEXT NOT NULL,
    "description" TEXT,
    "events" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "property_ids" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "disabled_reason" TEXT,
    "disabled_at" TIMESTAMPTZ(3),
    "secret_enc" TEXT NOT NULL,
    "secret_last4" TEXT NOT NULL,
    "previous_secret_enc" TEXT,
    "previous_secret_expires_at" TIMESTAMPTZ(3),
    "secret_rotated_at" TIMESTAMPTZ(3),
    "failing_since" TIMESTAMPTZ(3),
    "consecutive_failures" INTEGER NOT NULL DEFAULT 0,
    "last_success_at" TIMESTAMPTZ(3),
    "last_failure_at" TIMESTAMPTZ(3),
    "created_by_id" UUID,
    "created_by_name" TEXT,
    "api_key_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "webhook_endpoints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_deliveries" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "endpoint_id" UUID NOT NULL,
    "event_id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "property_id" UUID,
    "payload" JSONB NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "next_attempt_at" TIMESTAMPTZ(3),
    "last_attempt_at" TIMESTAMPTZ(3),
    "locked_until" TIMESTAMPTZ(3),
    "response_status" INTEGER,
    "duration_ms" INTEGER,
    "error" TEXT,
    "request_headers" JSONB,
    "response_headers" JSONB,
    "response_body" TEXT,
    "attempt_log" JSONB NOT NULL DEFAULT '[]',
    "is_test" BOOLEAN NOT NULL DEFAULT false,
    "replay_of" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "webhook_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "platform_recovery_codes_platform_user_id_idx" ON "platform_recovery_codes"("platform_user_id");

-- CreateIndex
CREATE INDEX "platform_sessions_platform_user_id_created_at_idx" ON "platform_sessions"("platform_user_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "platform_refresh_tokens_token_hash_key" ON "platform_refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "platform_refresh_tokens_session_id_idx" ON "platform_refresh_tokens"("session_id");

-- CreateIndex
CREATE INDEX "platform_audit_logs_created_at_idx" ON "platform_audit_logs"("created_at" DESC);

-- CreateIndex
CREATE INDEX "platform_audit_logs_actor_platform_user_id_created_at_idx" ON "platform_audit_logs"("actor_platform_user_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "platform_audit_logs_tenant_id_created_at_idx" ON "platform_audit_logs"("tenant_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "coupons_code_key" ON "coupons"("code");

-- CreateIndex
CREATE INDEX "coupon_redemptions_tenant_id_idx" ON "coupon_redemptions"("tenant_id");

-- CreateIndex
CREATE INDEX "coupon_redemptions_coupon_id_idx" ON "coupon_redemptions"("coupon_id");

-- CreateIndex
CREATE INDEX "announcements_starts_at_idx" ON "announcements"("starts_at");

-- CreateIndex
CREATE INDEX "announcement_receipts_tenant_id_idx" ON "announcement_receipts"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "announcement_receipts_announcement_id_user_id_key" ON "announcement_receipts"("announcement_id", "user_id");

-- CreateIndex
CREATE UNIQUE INDEX "support_requests_seq_key" ON "support_requests"("seq");

-- CreateIndex
CREATE INDEX "support_requests_tenant_id_created_at_idx" ON "support_requests"("tenant_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "support_requests_status_first_response_due_idx" ON "support_requests"("status", "first_response_due");

-- CreateIndex
CREATE INDEX "support_messages_request_id_created_at_idx" ON "support_messages"("request_id", "created_at");

-- CreateIndex
CREATE INDEX "support_attachments_tenant_id_idx" ON "support_attachments"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "impersonation_sessions_handoff_code_hash_key" ON "impersonation_sessions"("handoff_code_hash");

-- CreateIndex
CREATE INDEX "impersonation_sessions_tenant_id_started_at_idx" ON "impersonation_sessions"("tenant_id", "started_at" DESC);

-- CreateIndex
CREATE INDEX "impersonation_sessions_platform_user_id_started_at_idx" ON "impersonation_sessions"("platform_user_id", "started_at" DESC);

-- CreateIndex
CREATE INDEX "tenant_offboardings_tenant_id_idx" ON "tenant_offboardings"("tenant_id");

-- CreateIndex
CREATE INDEX "tenant_offboardings_status_delete_after_idx" ON "tenant_offboardings"("status", "delete_after");

-- CreateIndex
CREATE INDEX "data_exports_tenant_id_created_at_idx" ON "data_exports"("tenant_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "tenant_databases_tenant_id_key" ON "tenant_databases"("tenant_id");

-- CreateIndex
CREATE INDEX "db_provisionings_tenant_id_started_at_idx" ON "db_provisionings"("tenant_id", "started_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "public_listings_slug_key" ON "public_listings"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "public_listings_custom_domain_key" ON "public_listings"("custom_domain");

-- CreateIndex
CREATE INDEX "public_listings_tenant_id_idx" ON "public_listings"("tenant_id");

-- CreateIndex
CREATE INDEX "public_listings_city_idx" ON "public_listings"("city");

-- CreateIndex
CREATE UNIQUE INDEX "owner_setup_tokens_token_hash_key" ON "owner_setup_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "owner_setup_tokens_tenant_id_idx" ON "owner_setup_tokens"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "api_keys_prefix_key" ON "api_keys"("prefix");

-- CreateIndex
CREATE INDEX "api_keys_tenant_id_idx" ON "api_keys"("tenant_id");

-- CreateIndex
CREATE INDEX "api_usage_daily_tenant_id_date_idx" ON "api_usage_daily"("tenant_id", "date");

-- CreateIndex
CREATE UNIQUE INDEX "api_usage_daily_api_key_id_date_key" ON "api_usage_daily"("api_key_id", "date");

-- CreateIndex
CREATE UNIQUE INDEX "email_domains_tenant_id_key" ON "email_domains"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "email_domains_domain_key" ON "email_domains"("domain");

-- CreateIndex
CREATE INDEX "sms_sender_requests_tenant_id_idx" ON "sms_sender_requests"("tenant_id");

-- CreateIndex
CREATE INDEX "sms_sender_requests_status_idx" ON "sms_sender_requests"("status");

-- CreateIndex
CREATE UNIQUE INDEX "staff_portal_domains_tenant_id_key" ON "staff_portal_domains"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "staff_portal_domains_domain_key" ON "staff_portal_domains"("domain");

-- CreateIndex
CREATE INDEX "webhook_endpoints_tenant_id_idx" ON "webhook_endpoints"("tenant_id");

-- CreateIndex
CREATE INDEX "webhook_deliveries_endpoint_id_created_at_idx" ON "webhook_deliveries"("endpoint_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "webhook_deliveries_status_next_attempt_at_idx" ON "webhook_deliveries"("status", "next_attempt_at");

-- CreateIndex
CREATE INDEX "webhook_deliveries_tenant_id_created_at_idx" ON "webhook_deliveries"("tenant_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "platform_users_invite_token_hash_key" ON "platform_users"("invite_token_hash");

-- AddForeignKey
ALTER TABLE "platform_recovery_codes" ADD CONSTRAINT "platform_recovery_codes_platform_user_id_fkey" FOREIGN KEY ("platform_user_id") REFERENCES "platform_users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "platform_sessions" ADD CONSTRAINT "platform_sessions_platform_user_id_fkey" FOREIGN KEY ("platform_user_id") REFERENCES "platform_users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "platform_refresh_tokens" ADD CONSTRAINT "platform_refresh_tokens_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "platform_sessions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "announcement_receipts" ADD CONSTRAINT "announcement_receipts_announcement_id_fkey" FOREIGN KEY ("announcement_id") REFERENCES "announcements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "support_messages" ADD CONSTRAINT "support_messages_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "support_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhook_endpoints" ADD CONSTRAINT "webhook_endpoints_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_endpoint_id_fkey" FOREIGN KEY ("endpoint_id") REFERENCES "webhook_endpoints"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- -----------------------------------------------------------------------------
-- Integrity rules Prisma cannot express.
-- -----------------------------------------------------------------------------
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_one_discount" CHECK ((percent_off IS NULL) <> (amount_off_kobo IS NULL));
ALTER TABLE "coupons" ADD CONSTRAINT "coupons_percent" CHECK (percent_off IS NULL OR percent_off BETWEEN 1 AND 100);
-- One active coupon per tenant.
CREATE UNIQUE INDEX "coupon_redemptions_one_active" ON "coupon_redemptions" ("tenant_id") WHERE active;
-- One active impersonation per platform user.
CREATE UNIQUE INDEX "impersonation_one_active" ON "impersonation_sessions" ("platform_user_id") WHERE ended_at IS NULL;
-- One running export per tenant.
CREATE UNIQUE INDEX "data_exports_one_running" ON "data_exports" ("tenant_id") WHERE status IN ('QUEUED', 'RUNNING');
-- One current SMS sender request per tenant.
CREATE UNIQUE INDEX "sms_sender_one_current" ON "sms_sender_requests" ("tenant_id") WHERE current;
-- One open offboarding per tenant.
CREATE UNIQUE INDEX "tenant_offboardings_one_open" ON "tenant_offboardings" ("tenant_id") WHERE status IN ('EXPORTING', 'GRACE', 'DELETING');
CREATE INDEX "webhook_deliveries_due" ON "webhook_deliveries" ("next_attempt_at") WHERE status IN ('PENDING', 'RETRYING');

-- -----------------------------------------------------------------------------
-- Platform audit log: append-only for every role (like audit_logs).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION platform_audit_logs_block_mutation() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'platform_audit_logs is append-only: % is not allowed', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END
$$;
CREATE TRIGGER platform_audit_logs_append_only
  BEFORE UPDATE OR DELETE ON platform_audit_logs
  FOR EACH ROW EXECUTE FUNCTION platform_audit_logs_block_mutation();
CREATE TRIGGER platform_audit_logs_no_truncate
  BEFORE TRUNCATE ON platform_audit_logs
  FOR EACH STATEMENT EXECUTE FUNCTION platform_audit_logs_block_mutation();

-- -----------------------------------------------------------------------------
-- Tenant purge authorisation. The append-only ledgers (audit_logs,
-- folio_entries, guest_invoices, receipts) refuse UPDATE and DELETE for every
-- role. Two legitimate deletions exist: the NDPA offboarding deletion after the
-- 30-day grace, and purging the stale shared copy of a tenant that moved to a
-- dedicated database. `app_begin_tenant_purge(tenant)` (hotel_platform only)
-- checks that one of them is under way for that tenant and records the
-- current transaction id; the triggers then let DELETE (never UPDATE) of that
-- tenant's rows through, inside that transaction only.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_private.tenant_purges (
  tenant_id  uuid        NOT NULL,
  txid       bigint      NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, txid)
);
REVOKE ALL ON app_private.tenant_purges FROM PUBLIC;

CREATE OR REPLACE FUNCTION app_private.purge_allowed(p_tenant uuid) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path = pg_catalog, pg_temp
AS $$
  SELECT p_tenant IS NOT NULL AND EXISTS (
    SELECT 1 FROM app_private.tenant_purges WHERE tenant_id = p_tenant AND txid = txid_current()
  )
$$;
REVOKE ALL ON FUNCTION app_private.purge_allowed(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_private.purge_allowed(uuid) TO hotel_app, hotel_platform;

CREATE OR REPLACE FUNCTION app_begin_tenant_purge(p_tenant uuid) RETURNS void
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT (
    EXISTS (SELECT 1 FROM tenant_offboardings WHERE tenant_id = p_tenant AND status = 'DELETING')
    OR EXISTS (SELECT 1 FROM tenant_databases WHERE tenant_id = p_tenant AND mode = 'DEDICATED' AND status = 'ACTIVE')
  ) THEN
    RAISE EXCEPTION 'tenant % is not being purged', p_tenant USING ERRCODE = 'insufficient_privilege';
  END IF;
  DELETE FROM app_private.tenant_purges WHERE created_at < now() - interval '1 day';
  INSERT INTO app_private.tenant_purges (tenant_id, txid) VALUES (p_tenant, txid_current())
    ON CONFLICT DO NOTHING;
END
$$;
REVOKE ALL ON FUNCTION app_begin_tenant_purge(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_begin_tenant_purge(uuid) TO hotel_platform;

CREATE OR REPLACE FUNCTION audit_logs_block_mutation() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  -- Nested IF: PL/pgSQL does not short-circuit AND, and OLD is unset for TRUNCATE.
  IF TG_OP = 'DELETE' THEN
    IF app_private.purge_allowed(OLD.tenant_id) THEN
      RETURN OLD;
    END IF;
  END IF;
  RAISE EXCEPTION 'audit_logs is append-only: % is not allowed', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END
$$;

CREATE OR REPLACE FUNCTION folio_entries_block_mutation() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  -- Nested IF: PL/pgSQL does not short-circuit AND, and OLD is unset for TRUNCATE.
  IF TG_OP = 'DELETE' THEN
    IF app_private.purge_allowed(OLD.tenant_id) THEN
      RETURN OLD;
    END IF;
  END IF;
  RAISE EXCEPTION '% is append-only: % is not allowed (post a VOID entry instead)', TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'insufficient_privilege';
END
$$;

GRANT DELETE ON audit_logs, folio_entries, guest_invoices, receipts TO hotel_platform;

-- -----------------------------------------------------------------------------
-- RLS on the new tables.
--   Tenant-scoped control-plane tables (hotel reads them through a signed
--   tenant context on the shared database) and the data-plane webhook tables:
--   tenant_isolation for hotel_app, platform_access for hotel_platform.
--   Platform-only tables: RLS on with platform_access only; hotel_app has no
--   grants at all.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'coupon_redemptions', 'announcement_receipts', 'support_requests', 'support_messages', 'support_attachments',
    'impersonation_sessions', 'data_exports', 'api_keys', 'api_usage_daily', 'white_label_settings',
    'email_domains', 'sms_sender_requests', 'staff_portal_domains', 'sso_configs',
    'webhook_endpoints', 'webhook_deliveries'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I FOR ALL TO hotel_app
         USING (tenant_id = (SELECT app_current_tenant_id()))
         WITH CHECK (tenant_id = (SELECT app_current_tenant_id()))', t);
    EXECUTE format(
      'CREATE POLICY platform_access ON %I FOR ALL TO hotel_platform
         USING (true) WITH CHECK (true)', t);
  END LOOP;

  FOREACH t IN ARRAY ARRAY[
    'platform_recovery_codes', 'platform_sessions', 'platform_refresh_tokens', 'platform_audit_logs',
    'coupons', 'announcements', 'tenant_offboardings', 'tenant_databases', 'db_provisionings',
    'public_listings', 'job_runs', 'owner_setup_tokens'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY platform_access ON %I FOR ALL TO hotel_platform
         USING (true) WITH CHECK (true)', t);
  END LOOP;
END
$$;

-- -----------------------------------------------------------------------------
-- Grants.
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  announcement_receipts, support_requests, support_messages, support_attachments,
  data_exports, api_keys, white_label_settings, email_domains, sms_sender_requests,
  staff_portal_domains, sso_configs, webhook_endpoints, webhook_deliveries
TO hotel_app;
GRANT SELECT ON coupon_redemptions, api_usage_daily TO hotel_app;
GRANT SELECT, UPDATE ON impersonation_sessions TO hotel_app;
GRANT USAGE, SELECT ON SEQUENCE support_requests_seq_seq TO hotel_app, hotel_platform;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  platform_recovery_codes, platform_sessions, platform_refresh_tokens,
  coupons, coupon_redemptions, announcements, announcement_receipts,
  support_requests, support_messages, support_attachments, impersonation_sessions,
  tenant_offboardings, data_exports, tenant_databases, db_provisionings, public_listings,
  job_runs, owner_setup_tokens, api_keys, api_usage_daily,
  white_label_settings, email_domains, sms_sender_requests, staff_portal_domains, sso_configs,
  webhook_endpoints, webhook_deliveries
TO hotel_platform;
GRANT SELECT, INSERT ON platform_audit_logs TO hotel_platform;

-- -----------------------------------------------------------------------------
-- Dedicated-database cutover gate. Every tenant transaction on this database
-- starts with `app_tenant_gate(tenant)`: it takes a shared advisory lock for
-- the tenant (so the cutover can wait for in-flight transactions to drain by
-- taking the exclusive lock once) and says whether the tenant's data is
-- still served here: 'ok', 'read_only' (cutover window: the API rolls back
-- any transaction that wrote) or 'moved' (served by its dedicated database;
-- the API answers 409 TENANT_MIGRATING and refreshes its routing).
-- In a dedicated database tenant_databases is empty, so the answer is 'ok'.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION app_tenant_gate(p_tenant uuid) RETURNS text
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = public, pg_temp
AS $$
DECLARE
  v_mode text;
  v_status text;
BEGIN
  PERFORM pg_advisory_xact_lock_shared(hashtextextended('tenant-gate:' || p_tenant::text, 0));
  SELECT mode, status INTO v_mode, v_status FROM tenant_databases WHERE tenant_id = p_tenant;
  IF v_mode = 'DEDICATED' AND v_status = 'ACTIVE' THEN
    RETURN 'moved';
  ELSIF v_status = 'CUTOVER' THEN
    RETURN 'read_only';
  END IF;
  RETURN 'ok';
END
$$;
REVOKE ALL ON FUNCTION app_tenant_gate(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_tenant_gate(uuid) TO hotel_app, hotel_platform;
