-- M7: Brand Studio themes, booking forms, paid extras, pickup points and transfers, setup wizard
-- (tables generated by Prisma; RLS, grants, triggers and the data migration written by hand below).

-- CreateEnum
CREATE TYPE "ExtraCategory" AS ENUM ('TRANSPORT', 'FOOD', 'EARLY_LATE', 'CELEBRATION', 'WELLNESS', 'OTHER');

-- CreateEnum
CREATE TYPE "ExtraPricing" AS ENUM ('PER_STAY', 'PER_NIGHT', 'PER_PERSON', 'PER_PERSON_PER_NIGHT', 'PER_UNIT');

-- CreateEnum
CREATE TYPE "ExtraKind" AS ENUM ('STANDARD', 'EARLY_CHECK_IN', 'LATE_CHECK_OUT');

-- CreateEnum
CREATE TYPE "PickupKind" AS ENUM ('AIRPORT', 'MOTOR_PARK', 'TRAIN_STATION', 'JETTY', 'OTHER');

-- CreateEnum
CREATE TYPE "TransferDirection" AS ENUM ('ARRIVAL', 'DEPARTURE');

-- CreateEnum
CREATE TYPE "TransferStatus" AS ENUM ('REQUESTED', 'CONFIRMED', 'DRIVER_ASSIGNED', 'EN_ROUTE', 'PICKED_UP', 'COMPLETED', 'NO_SHOW', 'CANCELLED');

-- AlterTable
ALTER TABLE "reservations" ADD COLUMN     "form_answers" JSONB,
ADD COLUMN     "form_channel" TEXT,
ADD COLUMN     "form_submitted_at" TIMESTAMPTZ(3),
ADD COLUMN     "form_version_id" UUID;

-- CreateTable
CREATE TABLE "site_themes" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID,
    "scope" TEXT NOT NULL DEFAULT 'PROPERTY',
    "draft" JSONB NOT NULL,
    "draft_updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "draft_updated_by_id" UUID,
    "draft_updated_by_name" TEXT,
    "published_version_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "site_themes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "site_theme_versions" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "theme_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "content" JSONB NOT NULL,
    "note" TEXT,
    "published_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_by_id" UUID,
    "published_by_name" TEXT,

    CONSTRAINT "site_theme_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "site_assets" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "kind" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "bytes" INTEGER NOT NULL,
    "stripped_bytes" INTEGER NOT NULL DEFAULT 0,
    "original_name" TEXT,
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "site_assets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "booking_forms" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "preset_id" TEXT,
    "draft_fields" JSONB NOT NULL,
    "draft_updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "draft_updated_by_id" UUID,
    "draft_updated_by_name" TEXT,
    "published_version_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "booking_forms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "booking_form_versions" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "form_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "fields" JSONB NOT NULL,
    "diff" JSONB NOT NULL DEFAULT '{}',
    "note" TEXT,
    "published_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "published_by_id" UUID,
    "published_by_name" TEXT,

    CONSTRAINT "booking_form_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "form_uploads" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "field_key" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "size" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'TEMP',
    "reservation_id" UUID,
    "scan_engine" TEXT,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "attached_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "form_uploads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "extras" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "image_url" TEXT,
    "category" "ExtraCategory" NOT NULL DEFAULT 'OTHER',
    "kind" "ExtraKind" NOT NULL DEFAULT 'STANDARD',
    "pricing" "ExtraPricing" NOT NULL DEFAULT 'PER_STAY',
    "price_kobo" INTEGER NOT NULL,
    "max_units" INTEGER,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "channels" TEXT[] DEFAULT ARRAY['MARKETPLACE', 'BOOKING_SITE', 'FRONT_DESK']::TEXT[],
    "availability" JSONB NOT NULL DEFAULT '{}',
    "daily_cap" INTEGER,
    "lead_time_hours" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "extras_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pickup_points" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "short_name" TEXT,
    "kind" "PickupKind" NOT NULL,
    "city" TEXT NOT NULL,
    "address" TEXT,
    "price_kobo" INTEGER NOT NULL,
    "drop_off_price_kobo" INTEGER,
    "vehicle_options" JSONB NOT NULL DEFAULT '[]',
    "lead_time_hours" INTEGER NOT NULL DEFAULT 6,
    "operating_hours" JSONB,
    "notes_for_guest" TEXT,
    "taxable" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "pickup_points_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transport_companies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "short_name" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "transport_companies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "train_routes" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "operator" TEXT NOT NULL,
    "stations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "services" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "train_routes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "local_transport_companies" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "short_name" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "local_transport_companies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reservation_extras" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "reservation_id" UUID NOT NULL,
    "extra_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "category" "ExtraCategory" NOT NULL,
    "pricing" "ExtraPricing" NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "persons" INTEGER,
    "nights" INTEGER,
    "unit_price_kobo" INTEGER NOT NULL,
    "amount_kobo" INTEGER NOT NULL,
    "net_kobo" INTEGER NOT NULL,
    "tax_kobo" INTEGER NOT NULL,
    "tax_components" JSONB NOT NULL DEFAULT '[]',
    "description" TEXT NOT NULL,
    "service_dates" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "source" TEXT NOT NULL DEFAULT 'ONLINE',
    "folio_entry_id" UUID,
    "posted_at" TIMESTAMPTZ(3),
    "cancelled_at" TIMESTAMPTZ(3),
    "created_by_id" UUID,
    "created_by_name" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "reservation_extras_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transfers" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "reservation_id" UUID NOT NULL,
    "direction" "TransferDirection" NOT NULL,
    "status" "TransferStatus" NOT NULL DEFAULT 'REQUESTED',
    "pickup_point_id" UUID NOT NULL,
    "pickup_point_name" TEXT NOT NULL,
    "kind" "PickupKind" NOT NULL,
    "details" JSONB NOT NULL DEFAULT '{}',
    "scheduled_at" TIMESTAMPTZ(3) NOT NULL,
    "passengers" INTEGER NOT NULL DEFAULT 1,
    "luggage" INTEGER,
    "vehicle_option_id" TEXT,
    "vehicle_name" TEXT NOT NULL,
    "vehicle_max_passengers" INTEGER NOT NULL DEFAULT 4,
    "amount_kobo" INTEGER NOT NULL,
    "net_kobo" INTEGER NOT NULL,
    "tax_kobo" INTEGER NOT NULL,
    "tax_components" JSONB NOT NULL DEFAULT '[]',
    "contact_phone" TEXT,
    "driver_name" TEXT,
    "driver_phone" TEXT,
    "vehicle_plate" TEXT,
    "vehicle_description" TEXT,
    "assigned_at" TIMESTAMPTZ(3),
    "delay_note" TEXT,
    "notes" TEXT,
    "events" JSONB NOT NULL DEFAULT '[]',
    "source" TEXT NOT NULL DEFAULT 'ONLINE',
    "folio_entry_id" UUID,
    "posted_at" TIMESTAMPTZ(3),
    "last_notified_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "transfers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "setup_progress" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "hotel_type" TEXT,
    "steps" JSONB NOT NULL DEFAULT '{}',
    "started_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "setup_progress_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "site_themes_tenant_id_idx" ON "site_themes"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "site_themes_tenant_id_property_id_key" ON "site_themes"("tenant_id", "property_id");

-- CreateIndex
CREATE INDEX "site_theme_versions_tenant_id_idx" ON "site_theme_versions"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "site_theme_versions_theme_id_version_key" ON "site_theme_versions"("theme_id", "version");

-- CreateIndex
CREATE INDEX "site_assets_tenant_id_created_at_idx" ON "site_assets"("tenant_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "site_assets_tenant_id_file_name_key" ON "site_assets"("tenant_id", "file_name");

-- CreateIndex
CREATE UNIQUE INDEX "booking_forms_property_id_key" ON "booking_forms"("property_id");

-- CreateIndex
CREATE INDEX "booking_forms_tenant_id_idx" ON "booking_forms"("tenant_id");

-- CreateIndex
CREATE INDEX "booking_form_versions_tenant_id_idx" ON "booking_form_versions"("tenant_id");

-- CreateIndex
CREATE INDEX "booking_form_versions_property_id_idx" ON "booking_form_versions"("property_id");

-- CreateIndex
CREATE UNIQUE INDEX "booking_form_versions_form_id_version_key" ON "booking_form_versions"("form_id", "version");

-- CreateIndex
CREATE INDEX "form_uploads_tenant_id_status_expires_at_idx" ON "form_uploads"("tenant_id", "status", "expires_at");

-- CreateIndex
CREATE INDEX "form_uploads_reservation_id_idx" ON "form_uploads"("reservation_id");

-- CreateIndex
CREATE INDEX "form_uploads_property_id_idx" ON "form_uploads"("property_id");

-- CreateIndex
CREATE INDEX "extras_tenant_id_idx" ON "extras"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "extras_property_id_name_key" ON "extras"("property_id", "name");

-- CreateIndex
CREATE INDEX "pickup_points_tenant_id_idx" ON "pickup_points"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "pickup_points_property_id_name_key" ON "pickup_points"("property_id", "name");

-- CreateIndex
CREATE UNIQUE INDEX "transport_companies_name_key" ON "transport_companies"("name");

-- CreateIndex
CREATE UNIQUE INDEX "train_routes_name_key" ON "train_routes"("name");

-- CreateIndex
CREATE UNIQUE INDEX "local_transport_companies_tenant_id_name_key" ON "local_transport_companies"("tenant_id", "name");

-- CreateIndex
CREATE INDEX "reservation_extras_tenant_id_idx" ON "reservation_extras"("tenant_id");

-- CreateIndex
CREATE INDEX "reservation_extras_reservation_id_idx" ON "reservation_extras"("reservation_id");

-- CreateIndex
CREATE INDEX "reservation_extras_extra_id_status_idx" ON "reservation_extras"("extra_id", "status");

-- CreateIndex
CREATE INDEX "transfers_tenant_id_idx" ON "transfers"("tenant_id");

-- CreateIndex
CREATE INDEX "transfers_reservation_id_idx" ON "transfers"("reservation_id");

-- CreateIndex
CREATE INDEX "transfers_property_id_scheduled_at_idx" ON "transfers"("property_id", "scheduled_at");

-- CreateIndex
CREATE UNIQUE INDEX "setup_progress_property_id_key" ON "setup_progress"("property_id");

-- CreateIndex
CREATE INDEX "setup_progress_tenant_id_idx" ON "setup_progress"("tenant_id");

-- AddForeignKey
ALTER TABLE "site_themes" ADD CONSTRAINT "site_themes_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_themes" ADD CONSTRAINT "site_themes_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_theme_versions" ADD CONSTRAINT "site_theme_versions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_theme_versions" ADD CONSTRAINT "site_theme_versions_theme_id_fkey" FOREIGN KEY ("theme_id") REFERENCES "site_themes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "site_assets" ADD CONSTRAINT "site_assets_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_forms" ADD CONSTRAINT "booking_forms_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_forms" ADD CONSTRAINT "booking_forms_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_form_versions" ADD CONSTRAINT "booking_form_versions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_form_versions" ADD CONSTRAINT "booking_form_versions_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "booking_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "form_uploads" ADD CONSTRAINT "form_uploads_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extras" ADD CONSTRAINT "extras_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extras" ADD CONSTRAINT "extras_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pickup_points" ADD CONSTRAINT "pickup_points_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pickup_points" ADD CONSTRAINT "pickup_points_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "local_transport_companies" ADD CONSTRAINT "local_transport_companies_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservation_extras" ADD CONSTRAINT "reservation_extras_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservation_extras" ADD CONSTRAINT "reservation_extras_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservation_extras" ADD CONSTRAINT "reservation_extras_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservation_extras" ADD CONSTRAINT "reservation_extras_extra_id_fkey" FOREIGN KEY ("extra_id") REFERENCES "extras"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_pickup_point_id_fkey" FOREIGN KEY ("pickup_point_id") REFERENCES "pickup_points"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "setup_progress" ADD CONSTRAINT "setup_progress_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "setup_progress" ADD CONSTRAINT "setup_progress_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- -----------------------------------------------------------------------------
-- Integrity rules Prisma cannot express.
-- -----------------------------------------------------------------------------
-- One group-root theme per tenant (property_id NULL escapes the composite unique).
CREATE UNIQUE INDEX "site_themes_one_group_root" ON "site_themes" ("tenant_id") WHERE "property_id" IS NULL;
ALTER TABLE "site_themes" ADD CONSTRAINT "site_themes_scope_check"
  CHECK (("scope" = 'GROUP' AND "property_id" IS NULL) OR ("scope" = 'PROPERTY' AND "property_id" IS NOT NULL));
ALTER TABLE "site_assets" ADD CONSTRAINT "site_assets_kind_check" CHECK ("kind" IN ('logo', 'favicon', 'image'));
ALTER TABLE "form_uploads" ADD CONSTRAINT "form_uploads_status_check" CHECK ("status" IN ('TEMP', 'ATTACHED', 'DELETED'));
ALTER TABLE "reservation_extras" ADD CONSTRAINT "reservation_extras_status_check" CHECK ("status" IN ('ACTIVE', 'CANCELLED'));
ALTER TABLE "reservation_extras" ADD CONSTRAINT "reservation_extras_source_check" CHECK ("source" IN ('ONLINE', 'FRONT_DESK'));
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_source_check" CHECK ("source" IN ('ONLINE', 'FRONT_DESK'));
ALTER TABLE "extras" ADD CONSTRAINT "extras_price_check" CHECK ("price_kobo" > 0 AND ("max_units" IS NULL OR "max_units" BETWEEN 1 AND 50));
ALTER TABLE "pickup_points" ADD CONSTRAINT "pickup_points_price_check" CHECK ("price_kobo" >= 0 AND ("drop_off_price_kobo" IS NULL OR "drop_off_price_kobo" >= 0));
-- At most one live arrival pickup and one live departure drop-off per reservation.
CREATE UNIQUE INDEX "transfers_one_live_per_direction" ON "transfers" ("reservation_id", "direction") WHERE "status" NOT IN ('CANCELLED', 'NO_SHOW');
CREATE INDEX "reservations_form_version_idx" ON "reservations" ("form_version_id") WHERE "form_version_id" IS NOT NULL;

-- Published booking form versions are immutable: reservations point at them.
CREATE OR REPLACE FUNCTION booking_form_versions_block_update() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'booking_form_versions are immutable once published: % is not allowed', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END
$$;
CREATE TRIGGER booking_form_versions_immutable
  BEFORE UPDATE ON booking_form_versions
  FOR EACH ROW EXECUTE FUNCTION booking_form_versions_block_update();
-- Published theme versions: never changed (old ones are pruned by DELETE).
CREATE TRIGGER site_theme_versions_immutable
  BEFORE UPDATE ON site_theme_versions
  FOR EACH ROW EXECUTE FUNCTION booking_form_versions_block_update();

-- -----------------------------------------------------------------------------
-- RLS on the new tenant tables (data plane: they move with a dedicated database).
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'site_themes', 'site_theme_versions', 'site_assets', 'booking_forms', 'booking_form_versions', 'form_uploads',
    'extras', 'pickup_points', 'local_transport_companies', 'reservation_extras', 'transfers', 'setup_progress'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I FOR ALL TO hotel_app
         USING (tenant_id = (SELECT app_current_tenant_id()))
         WITH CHECK (tenant_id = (SELECT app_current_tenant_id()))', t);
    EXECUTE format(
      'CREATE POLICY platform_access ON %I FOR ALL TO hotel_platform
         USING (true) WITH CHECK (true)', t);
  END LOOP;

  -- Platform catalogues (no tenant): readable by everyone, written by the seed / console only.
  FOREACH t IN ARRAY ARRAY['transport_companies', 'train_routes']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY read_all ON %I FOR SELECT USING (true)', t);
    EXECUTE format(
      'CREATE POLICY platform_access ON %I FOR ALL TO hotel_platform
         USING (true) WITH CHECK (true)', t);
  END LOOP;
END
$$;

-- -----------------------------------------------------------------------------
-- Grants.
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  site_themes, site_assets, booking_forms, form_uploads, extras, pickup_points,
  local_transport_companies, reservation_extras, transfers, setup_progress
TO hotel_app;
-- Versions: written once, pruned (themes) by the API; never updated.
GRANT SELECT, INSERT, DELETE ON site_theme_versions TO hotel_app;
GRANT SELECT, INSERT ON booking_form_versions TO hotel_app;
GRANT SELECT ON transport_companies, train_routes TO hotel_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  site_themes, site_theme_versions, site_assets, booking_forms, booking_form_versions, form_uploads,
  extras, pickup_points, local_transport_companies, reservation_extras, transfers, setup_progress,
  transport_companies, train_routes
TO hotel_platform;

-- -----------------------------------------------------------------------------
-- Data migration.
-- -----------------------------------------------------------------------------
-- New feature codes (the seed keeps names and descriptions up to date).
INSERT INTO features (code, name, description, category) VALUES
  ('brand_kit', 'Brand kit', 'Your logo, favicon and colours on your booking site, emails and invoices.', 'Growth'),
  ('site_templates_all', 'All booking-site templates', 'Choose from every booking-site template (Starter: Essentials and Editorial).', 'Growth'),
  ('site_sections', 'Section editor', 'Show, hide and reorder booking-site sections and choose light or dark.', 'Growth'),
  ('site_fonts', 'Font pairings', 'Choose the typefaces of your booking site from curated pairings.', 'Growth'),
  ('form_fields_unlimited', 'Unlimited form fields', 'Ask guests as many extra questions as you need when they book.', 'Guests'),
  ('form_conditional_logic', 'Conditional questions', 'Show booking-form questions only when an earlier answer calls for them.', 'Guests'),
  ('paid_extras', 'Paid extras and pickups', 'Sell breakfast, early check-in, celebrations and airport or motor-park pickups with the room.', 'Revenue'),
  ('form_file_uploads', 'File uploads in the booking form', 'Let guests attach documents such as an event invitation or a company letter.', 'Guests')
ON CONFLICT (code) DO NOTHING;

-- Plan features: brand_kit on every plan (it replaces Growth's booking_site_branding for logo and colours).
INSERT INTO plan_features (plan_id, feature_code)
SELECT p.id, f.code
FROM plans p
JOIN (VALUES
  ('starter', 'brand_kit'),
  ('growth', 'brand_kit'), ('growth', 'site_templates_all'), ('growth', 'site_sections'), ('growth', 'form_fields_unlimited'),
  ('growth', 'form_conditional_logic'), ('growth', 'paid_extras'),
  ('pro', 'brand_kit'), ('pro', 'site_templates_all'), ('pro', 'site_sections'), ('pro', 'site_fonts'), ('pro', 'form_fields_unlimited'),
  ('pro', 'form_conditional_logic'), ('pro', 'paid_extras'), ('pro', 'form_file_uploads'),
  ('enterprise', 'brand_kit'), ('enterprise', 'site_templates_all'), ('enterprise', 'site_sections'), ('enterprise', 'site_fonts'),
  ('enterprise', 'form_fields_unlimited'), ('enterprise', 'form_conditional_logic'), ('enterprise', 'paid_extras'),
  ('enterprise', 'form_file_uploads')
) AS f(plan_code, code) ON f.plan_code = p.code
WHERE EXISTS (SELECT 1 FROM features WHERE features.code = f.code)
ON CONFLICT DO NOTHING;

-- Limit: extra (library + custom) form fields. Starter 3, everyone else unlimited.
UPDATE plans SET limits = limits || jsonb_build_object('max_custom_form_fields', CASE WHEN code = 'starter' THEN 3 ELSE -1 END)
WHERE NOT (limits ? 'max_custom_form_fields');

-- booking_site_branding is now an alias of brand_kit: carry add-on / removal overrides over.
INSERT INTO tenant_feature_overrides (id, tenant_id, feature_code, enabled, note, created_at, updated_at)
SELECT gen_random_uuid(), o.tenant_id, 'brand_kit', o.enabled, COALESCE(o.note, 'Copied from booking_site_branding (M7 alias)'), now(), now()
FROM tenant_feature_overrides o
WHERE o.feature_code = 'booking_site_branding'
  AND EXISTS (SELECT 1 FROM features WHERE code = 'brand_kit')
ON CONFLICT (tenant_id, feature_code) DO NOTHING;

-- Every existing property gets a published Editorial theme from its M1 accent colour and logo
-- (sections null = the template's defaults; applied colours are computed by the API on first read).
WITH src AS (
  SELECT p.id AS property_id, p.tenant_id, gen_random_uuid() AS theme_id, gen_random_uuid() AS version_id,
         jsonb_build_object(
           'templateId', 'editorial',
           'brand', jsonb_build_object(
             'logoAssetId', NULL, 'faviconAssetId', NULL, 'logoUrl', p.logo_url, 'faviconUrl', NULL,
             'primary', CASE WHEN p.accent_color ~ '^#[0-9A-Fa-f]{6}$' THEN upper(p.accent_color) ELSE '#B4452A' END,
             'secondary', NULL, 'fontPairingId', NULL),
           'colourMode', 'SYSTEM',
           'sections', NULL
         ) AS content
  FROM properties p
  WHERE NOT EXISTS (SELECT 1 FROM site_themes t WHERE t.property_id = p.id)
), themes AS (
  INSERT INTO site_themes (id, tenant_id, property_id, scope, draft, draft_updated_at, published_version_id, created_at, updated_at)
  SELECT theme_id, tenant_id, property_id, 'PROPERTY', content, now(), version_id, now(), now() FROM src
  RETURNING id
)
INSERT INTO site_theme_versions (id, tenant_id, theme_id, version, content, note, published_at, published_by_name)
SELECT version_id, tenant_id, theme_id, 1, content, 'Created from the hotel profile (M7 migration)', now(), 'System'
FROM src WHERE theme_id IN (SELECT id FROM themes);

-- Hotels that existed before M7 have finished setting up.
INSERT INTO setup_progress (id, tenant_id, property_id, steps, started_at, completed_at, created_at, updated_at)
SELECT gen_random_uuid(), p.tenant_id, p.id, '{}'::jsonb, p.created_at, now(), now(), now()
FROM properties p
WHERE NOT EXISTS (SELECT 1 FROM setup_progress s WHERE s.property_id = p.id);
